// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from '@hey-api/client-fetch';
import type { GetApiMigrationCalculatePilotPropertiesData, GetApiRatingsGetData, GetApiRatingsGetResponse, GetApiPilotsAllData, GetApiPilotsAllResponse, GetApiPilotsProfileData, GetApiPilotsProfileResponse, GetApiResultsForPilotData, GetApiResultsForPilotResponse, GetApiDaystreakLeaderboardData, GetApiDaystreakLeaderboardResponse, GetApiCompetitionsCurrentData, GetApiCompetitionsCurrentResponse, GetApiDashboardData, GetApiDashboardResponse } from './types.gen';

export const client = createClient(createConfig());

export const getApiMigrationCalculatePilotProperties = <ThrowOnError extends boolean = false>(options?: Options<GetApiMigrationCalculatePilotPropertiesData, ThrowOnError>) => {
    return (options?.client ?? client).get<unknown, unknown, ThrowOnError>({
        ...options,
        url: '/api/migration/CalculatePilotProperties'
    });
};

export const getApiRatingsGet = <ThrowOnError extends boolean = false>(options?: Options<GetApiRatingsGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetApiRatingsGetResponse, unknown, ThrowOnError>({
        ...options,
        url: '/api/ratings/get'
    });
};

export const getApiPilotsAll = <ThrowOnError extends boolean = false>(options?: Options<GetApiPilotsAllData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetApiPilotsAllResponse, unknown, ThrowOnError>({
        ...options,
        url: '/api/pilots/All'
    });
};

export const getApiPilotsProfile = <ThrowOnError extends boolean = false>(options?: Options<GetApiPilotsProfileData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetApiPilotsProfileResponse, unknown, ThrowOnError>({
        ...options,
        url: '/api/pilots/Profile'
    });
};

export const getApiResultsForPilot = <ThrowOnError extends boolean = false>(options?: Options<GetApiResultsForPilotData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetApiResultsForPilotResponse, unknown, ThrowOnError>({
        ...options,
        url: '/api/results/ForPilot'
    });
};

export const getApiDaystreakLeaderboard = <ThrowOnError extends boolean = false>(options?: Options<GetApiDaystreakLeaderboardData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetApiDaystreakLeaderboardResponse, unknown, ThrowOnError>({
        ...options,
        url: '/api/daystreak/Leaderboard'
    });
};

export const getApiCompetitionsCurrent = <ThrowOnError extends boolean = false>(options?: Options<GetApiCompetitionsCurrentData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetApiCompetitionsCurrentResponse, unknown, ThrowOnError>({
        ...options,
        url: '/api/competitions/current'
    });
};

export const getApiDashboard = <ThrowOnError extends boolean = false>(options?: Options<GetApiDashboardData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetApiDashboardResponse, unknown, ThrowOnError>({
        ...options,
        url: '/api/dashboard'
    });
};