// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from '@hey-api/client-fetch';
import type { GetApiPilotStatisticsCountData, GetApiPilotStatisticsCountResponse, GetApiPilotStatisticsNewPilotsData, GetApiPilotStatisticsNewPilotsResponse, GetApiPilotStatisticsParticipationData, GetApiPilotStatisticsParticipationResponse, GetApiRatingsGetData, GetApiRatingsGetResponse, GetApiProfileData, GetApiProfileResponse, GetApiProfilePilotLookupData, GetApiProfilePilotLookupResponse, DeleteApiProfileClaimData, DeleteApiProfileClaimResponse, PostApiProfileClaimData, PostApiProfileClaimResponse, DeleteApiProfileAccountData, GetApiPilotsAllData, GetApiPilotsAllResponse, GetApiPilotsProfileData, GetApiPilotsProfileResponse, GetApiNotificationsData, GetApiNotificationsResponse, GetApiNotificationsUnreadCountData, GetApiNotificationsUnreadCountResponse, PostApiNotificationsReadData, PostApiNotificationsReadResponse, PostApiNotificationsReadAllData, PostApiNotificationsReadAllResponse, GetApiMigrationCalculatePilotPropertiesData, GetApiLandingGetData, GetApiLandingGetResponse, GetApiResultsForPilotData, GetApiResultsForPilotResponse, GetApiDaystreakLeaderboardData, GetApiDaystreakLeaderboardResponse, GetApiCupsGetData, GetApiCupsGetResponse, GetApiCompetitionsCurrentData, GetApiCompetitionsCurrentResponse, GetApiCompetitionsOverviewData, GetApiCompetitionsOverviewResponse, PostApiAuthGoogleData, PostApiAuthGoogleResponse, PostApiAuthRefreshData, PostApiAuthRefreshResponse, PostApiAuthLogoutData, GetApiAuthMeData, GetApiAuthMeResponse } from './types.gen';

export const client = createClient(createConfig());

export const getApiPilotStatisticsCount = <ThrowOnError extends boolean = false>(options?: Options<GetApiPilotStatisticsCountData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetApiPilotStatisticsCountResponse, unknown, ThrowOnError>({
        ...options,
        url: '/api/pilot-statistics/Count'
    });
};

export const getApiPilotStatisticsNewPilots = <ThrowOnError extends boolean = false>(options?: Options<GetApiPilotStatisticsNewPilotsData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetApiPilotStatisticsNewPilotsResponse, unknown, ThrowOnError>({
        ...options,
        url: '/api/pilot-statistics/NewPilots'
    });
};

export const getApiPilotStatisticsParticipation = <ThrowOnError extends boolean = false>(options?: Options<GetApiPilotStatisticsParticipationData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetApiPilotStatisticsParticipationResponse, unknown, ThrowOnError>({
        ...options,
        url: '/api/pilot-statistics/Participation'
    });
};

export const getApiRatingsGet = <ThrowOnError extends boolean = false>(options?: Options<GetApiRatingsGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetApiRatingsGetResponse, unknown, ThrowOnError>({
        ...options,
        url: '/api/ratings/get'
    });
};

export const getApiProfile = <ThrowOnError extends boolean = false>(options?: Options<GetApiProfileData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetApiProfileResponse, unknown, ThrowOnError>({
        ...options,
        url: '/api/profile'
    });
};

export const getApiProfilePilotLookup = <ThrowOnError extends boolean = false>(options?: Options<GetApiProfilePilotLookupData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetApiProfilePilotLookupResponse, unknown, ThrowOnError>({
        ...options,
        url: '/api/profile/pilot-lookup'
    });
};

export const deleteApiProfileClaim = <ThrowOnError extends boolean = false>(options?: Options<DeleteApiProfileClaimData, ThrowOnError>) => {
    return (options?.client ?? client).delete<DeleteApiProfileClaimResponse, unknown, ThrowOnError>({
        ...options,
        url: '/api/profile/claim'
    });
};

export const postApiProfileClaim = <ThrowOnError extends boolean = false>(options: Options<PostApiProfileClaimData, ThrowOnError>) => {
    return (options?.client ?? client).post<PostApiProfileClaimResponse, unknown, ThrowOnError>({
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        },
        url: '/api/profile/claim'
    });
};

export const deleteApiProfileAccount = <ThrowOnError extends boolean = false>(options?: Options<DeleteApiProfileAccountData, ThrowOnError>) => {
    return (options?.client ?? client).delete<unknown, unknown, ThrowOnError>({
        ...options,
        url: '/api/profile/account'
    });
};

export const getApiPilotsAll = <ThrowOnError extends boolean = false>(options?: Options<GetApiPilotsAllData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetApiPilotsAllResponse, unknown, ThrowOnError>({
        ...options,
        url: '/api/pilots/All'
    });
};

export const getApiPilotsProfile = <ThrowOnError extends boolean = false>(options?: Options<GetApiPilotsProfileData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetApiPilotsProfileResponse, unknown, ThrowOnError>({
        ...options,
        url: '/api/pilots/Profile'
    });
};

export const getApiNotifications = <ThrowOnError extends boolean = false>(options?: Options<GetApiNotificationsData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetApiNotificationsResponse, unknown, ThrowOnError>({
        ...options,
        url: '/api/notifications'
    });
};

export const getApiNotificationsUnreadCount = <ThrowOnError extends boolean = false>(options?: Options<GetApiNotificationsUnreadCountData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetApiNotificationsUnreadCountResponse, unknown, ThrowOnError>({
        ...options,
        url: '/api/notifications/unread-count'
    });
};

export const postApiNotificationsRead = <ThrowOnError extends boolean = false>(options: Options<PostApiNotificationsReadData, ThrowOnError>) => {
    return (options?.client ?? client).post<PostApiNotificationsReadResponse, unknown, ThrowOnError>({
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        },
        url: '/api/notifications/read'
    });
};

export const postApiNotificationsReadAll = <ThrowOnError extends boolean = false>(options?: Options<PostApiNotificationsReadAllData, ThrowOnError>) => {
    return (options?.client ?? client).post<PostApiNotificationsReadAllResponse, unknown, ThrowOnError>({
        ...options,
        url: '/api/notifications/read-all'
    });
};

export const getApiMigrationCalculatePilotProperties = <ThrowOnError extends boolean = false>(options?: Options<GetApiMigrationCalculatePilotPropertiesData, ThrowOnError>) => {
    return (options?.client ?? client).get<unknown, unknown, ThrowOnError>({
        ...options,
        url: '/api/migration/CalculatePilotProperties'
    });
};

export const getApiLandingGet = <ThrowOnError extends boolean = false>(options?: Options<GetApiLandingGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetApiLandingGetResponse, unknown, ThrowOnError>({
        ...options,
        url: '/api/landing/get'
    });
};

export const getApiResultsForPilot = <ThrowOnError extends boolean = false>(options?: Options<GetApiResultsForPilotData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetApiResultsForPilotResponse, unknown, ThrowOnError>({
        ...options,
        url: '/api/results/ForPilot'
    });
};

export const getApiDaystreakLeaderboard = <ThrowOnError extends boolean = false>(options?: Options<GetApiDaystreakLeaderboardData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetApiDaystreakLeaderboardResponse, unknown, ThrowOnError>({
        ...options,
        url: '/api/daystreak/Leaderboard'
    });
};

export const getApiCupsGet = <ThrowOnError extends boolean = false>(options?: Options<GetApiCupsGetData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetApiCupsGetResponse, unknown, ThrowOnError>({
        ...options,
        url: '/api/cups/get'
    });
};

export const getApiCompetitionsCurrent = <ThrowOnError extends boolean = false>(options?: Options<GetApiCompetitionsCurrentData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetApiCompetitionsCurrentResponse, unknown, ThrowOnError>({
        ...options,
        url: '/api/competitions/current'
    });
};

export const getApiCompetitionsOverview = <ThrowOnError extends boolean = false>(options?: Options<GetApiCompetitionsOverviewData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetApiCompetitionsOverviewResponse, unknown, ThrowOnError>({
        ...options,
        url: '/api/competitions/overview'
    });
};

export const postApiAuthGoogle = <ThrowOnError extends boolean = false>(options: Options<PostApiAuthGoogleData, ThrowOnError>) => {
    return (options?.client ?? client).post<PostApiAuthGoogleResponse, unknown, ThrowOnError>({
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        },
        url: '/api/auth/Google'
    });
};

export const postApiAuthRefresh = <ThrowOnError extends boolean = false>(options: Options<PostApiAuthRefreshData, ThrowOnError>) => {
    return (options?.client ?? client).post<PostApiAuthRefreshResponse, unknown, ThrowOnError>({
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        },
        url: '/api/auth/Refresh'
    });
};

export const postApiAuthLogout = <ThrowOnError extends boolean = false>(options: Options<PostApiAuthLogoutData, ThrowOnError>) => {
    return (options?.client ?? client).post<unknown, unknown, ThrowOnError>({
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        },
        url: '/api/auth/Logout'
    });
};

export const getApiAuthMe = <ThrowOnError extends boolean = false>(options?: Options<GetApiAuthMeData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetApiAuthMeResponse, unknown, ThrowOnError>({
        ...options,
        url: '/api/auth/Me'
    });
};