// This file is auto-generated by @hey-api/openapi-ts

export type CompetitionModel = {
    id: string;
    startedOn: string;
    state: CompetitionState;
    mapName: string;
    trackName: string;
    trackId: number;
    mapId: number;
    quadOfTheDay?: null | string;
};

export type CompetitionState = number;

export type DashboardModel = {
    competition?: null | CompetitionModel;
    results: Array<TrackTimeModel>;
    leaderboard: Array<SeasonResultModel>;
};

export type PilotAchievementModel = {
    name: string;
    earnedOn: string;
    title: string;
    description: string;
};

export type PilotProfileModel = {
    name: string;
    country: string;
    currentDayStreak: number;
    maxDayStreak: number;
    achievements: Array<PilotAchievementModel>;
    totalRaceDays: number;
    lastRaceDate?: null | string;
    firstRaceDate?: null | string;
    availableFreezes: number;
};

export type PilotResult = {
    date: string;
    points: number;
    trackTime: number;
};

export type SeasonResultModel = {
    playerName: string;
    points: number;
    country: string;
};

export type TrackTimeModel = {
    playerName: string;
    time: number;
    globalRank: number;
    localRank: number;
    modelName: string;
    country: string;
};

export type GetApiMigrationSomethingData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/migration/something';
};

export type GetApiMigrationSomethingResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiPilotsAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/pilots/All';
};

export type GetApiPilotsAllResponses = {
    /**
     * OK
     */
    200: Array<string>;
};

export type GetApiPilotsAllResponse = GetApiPilotsAllResponses[keyof GetApiPilotsAllResponses];

export type GetApiPilotsProfileData = {
    body?: never;
    path?: never;
    query?: {
        pilotName?: string;
    };
    url: '/api/pilots/Profile';
};

export type GetApiPilotsProfileResponses = {
    /**
     * OK
     */
    200: PilotProfileModel;
};

export type GetApiPilotsProfileResponse = GetApiPilotsProfileResponses[keyof GetApiPilotsProfileResponses];

export type GetApiResultsForPilotData = {
    body?: never;
    path?: never;
    query?: {
        pilotName?: string;
    };
    url: '/api/results/ForPilot';
};

export type GetApiResultsForPilotResponses = {
    /**
     * OK
     */
    200: Array<PilotResult>;
};

export type GetApiResultsForPilotResponse = GetApiResultsForPilotResponses[keyof GetApiResultsForPilotResponses];

export type GetApiCompetitionsCurrentData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/competitions/current';
};

export type GetApiCompetitionsCurrentResponses = {
    /**
     * OK
     */
    200: Array<CompetitionModel>;
};

export type GetApiCompetitionsCurrentResponse = GetApiCompetitionsCurrentResponses[keyof GetApiCompetitionsCurrentResponses];

export type GetApiDashboardData = {
    body?: never;
    path?: never;
    query?: {
        cupId?: string;
        date?: string;
    };
    url: '/api/dashboard';
};

export type GetApiDashboardResponses = {
    /**
     * OK
     */
    200: DashboardModel;
};

export type GetApiDashboardResponse = GetApiDashboardResponses[keyof GetApiDashboardResponses];