// This file is auto-generated by @hey-api/openapi-ts

export type CompetitionModel = {
    id: string;
    startedOn: string;
    state: CompetitionState;
    mapName: string;
    trackName: string;
    trackId: number;
    mapId: number;
    quadOfTheDay?: null | string;
    leagues?: LeagueOptions;
};

export type CompetitionState = number;

export type DashboardModel = {
    competition?: null | CompetitionModel;
    leaderboard: Array<LeagueLeaderboardModel>;
    seasonLeaderboard: Array<LeagueSeasonLeaderboard>;
};

export type LeagueLeaderboardModel = {
    league?: null | string;
    results: Array<LeaderboardResultModel>;
};

export type LeaderboardResultModel = {
    playerName: string;
    trackTime?: number;
    localRank?: number;
    globalRank?: number;
    modelName?: null | string;
    country: string;
};

export type LeagueSeasonLeaderboard = {
    league?: null | string;
    results: Array<SeasonResult>;
};

export type SeasonResult = {
    playerName: string;
    points?: number;
    rank?: number;
    country: string;
};

export type LeagueOptions = {
    enabled?: boolean;
    othersName?: string;
    definitions?: Array<LeagueDescriptor>;
};

export type LeagueDescriptor = {
    name?: string;
    size?: number;
    order?: number;
    color?: null | string;
};

export type PilotAchievementModel = {
    name: string;
    achievedOn: string | null;
    title: string;
    description: string;
};

export type PilotProfileModel = {
    name: string;
    country: string;
    currentDayStreak: number;
    maxDayStreak: number;
    achievements: Array<PilotAchievementModel>;
    totalRaceDays: number;
    lastRaceDate?: null | string;
    firstRaceDate?: null | string;
    availableFreezes: number;
    globalRating: number | null;
    league?: null | string;
    leagueColor?: null | string;
    ratingHistory: Array<PilotRatingHistoryPoint>;
};

export type PilotRatingHistoryPoint = {
    date: string;
    gapPercent?: number | null;
    rank: number;
};

export type PilotResult = {
    date: string;
    points: number;
    trackTime: number;
};

export type RatingModel = {
    calculatedOn: string;
    ratings: Array<PilotRatingModel>;
    droppedOutPilots: Array<PilotRatingModel>;
};

export type PilotRatingModel = {
    pilotId: number;
    pilotName: string;
    country?: null | string;
    averageGapPercent?: number | null;
    averageGapChange?: number | null;
    rank: number;
    rankChange?: number | null;
};

export type GetApiMigrationSomethingData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/migration/something';
};

export type GetApiMigrationSomethingResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiPilotsAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/pilots/All';
};

export type GetApiPilotsAllResponses = {
    /**
     * OK
     */
    200: Array<string>;
};

export type GetApiPilotsAllResponse = GetApiPilotsAllResponses[keyof GetApiPilotsAllResponses];

export type GetApiPilotsProfileData = {
    body?: never;
    path?: never;
    query?: {
        pilotName?: string;
    };
    url: '/api/pilots/Profile';
};

export type GetApiPilotsProfileResponses = {
    /**
     * OK
     */
    200: PilotProfileModel;
};

export type GetApiPilotsProfileResponse = GetApiPilotsProfileResponses[keyof GetApiPilotsProfileResponses];

export type GetApiResultsForPilotData = {
    body?: never;
    path?: never;
    query?: {
        pilotName?: string;
    };
    url: '/api/results/ForPilot';
};

export type GetApiResultsForPilotResponses = {
    /**
     * OK
     */
    200: Array<PilotResult>;
};

export type GetApiResultsForPilotResponse = GetApiResultsForPilotResponses[keyof GetApiResultsForPilotResponses];

export type GetApiCompetitionsCurrentData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/competitions/current';
};

export type GetApiCompetitionsCurrentResponses = {
    /**
     * OK
     */
    200: Array<CompetitionModel>;
};

export type GetApiCompetitionsCurrentResponse = GetApiCompetitionsCurrentResponses[keyof GetApiCompetitionsCurrentResponses];

export type GetApiDashboardData = {
    body?: never;
    path?: never;
    query?: {
        cupId?: string;
        date?: string;
    };
    url: '/api/dashboard';
};

export type GetApiDashboardResponses = {
    /**
     * OK
     */
    200: DashboardModel;
};

export type GetApiDashboardResponse = GetApiDashboardResponses[keyof GetApiDashboardResponses];

export type GetApiRatingsGetData = {
    body?: never;
    path?: never;
    query?: {
        cupId?: string;
    };
    url: '/api/ratings/get';
};

export type GetApiRatingsGetResponses = {
    /**
     * OK
     */
    200: RatingModel;
};

export type GetApiRatingsGetResponse = GetApiRatingsGetResponses[keyof GetApiRatingsGetResponses];