namespace Veloci.Logic.Services;

public static class TimeZoneService
{
    // Maps ISO 3166-1 alpha-2 country codes to their primary IANA timezone.
    // Countries spanning multiple zones use the capital/most populated zone.
    private static readonly Dictionary<string, string> CountryTimeZones = new()
    {
        ["AD"] = "Europe/Andorra",
        ["AE"] = "Asia/Dubai",
        ["AF"] = "Asia/Kabul",
        ["AL"] = "Europe/Tirane",
        ["AM"] = "Asia/Yerevan",
        ["AO"] = "Africa/Luanda",
        ["AR"] = "America/Argentina/Buenos_Aires",
        ["AT"] = "Europe/Vienna",
        ["AU"] = "Australia/Sydney",
        ["AZ"] = "Asia/Baku",
        ["BA"] = "Europe/Sarajevo",
        ["BD"] = "Asia/Dhaka",
        ["BE"] = "Europe/Brussels",
        ["BG"] = "Europe/Sofia",
        ["BH"] = "Asia/Bahrain",
        ["BO"] = "America/La_Paz",
        ["BR"] = "America/Sao_Paulo",
        ["BY"] = "Europe/Minsk",
        ["CA"] = "America/Toronto",
        ["CH"] = "Europe/Zurich",
        ["CL"] = "America/Santiago",
        ["CN"] = "Asia/Shanghai",
        ["CO"] = "America/Bogota",
        ["CY"] = "Asia/Nicosia",
        ["CZ"] = "Europe/Prague",
        ["DE"] = "Europe/Berlin",
        ["DK"] = "Europe/Copenhagen",
        ["DZ"] = "Africa/Algiers",
        ["EC"] = "America/Guayaquil",
        ["EE"] = "Europe/Tallinn",
        ["EG"] = "Africa/Cairo",
        ["ES"] = "Europe/Madrid",
        ["ET"] = "Africa/Addis_Ababa",
        ["FI"] = "Europe/Helsinki",
        ["FR"] = "Europe/Paris",
        ["GB"] = "Europe/London",
        ["GE"] = "Asia/Tbilisi",
        ["GH"] = "Africa/Accra",
        ["GR"] = "Europe/Athens",
        ["GT"] = "America/Guatemala",
        ["HK"] = "Asia/Hong_Kong",
        ["HR"] = "Europe/Zagreb",
        ["HU"] = "Europe/Budapest",
        ["ID"] = "Asia/Jakarta",
        ["IE"] = "Europe/Dublin",
        ["IL"] = "Asia/Jerusalem",
        ["IN"] = "Asia/Kolkata",
        ["IQ"] = "Asia/Baghdad",
        ["IR"] = "Asia/Tehran",
        ["IS"] = "Atlantic/Reykjavik",
        ["IT"] = "Europe/Rome",
        ["JO"] = "Asia/Amman",
        ["JP"] = "Asia/Tokyo",
        ["KE"] = "Africa/Nairobi",
        ["KG"] = "Asia/Bishkek",
        ["KH"] = "Asia/Phnom_Penh",
        ["KR"] = "Asia/Seoul",
        ["KW"] = "Asia/Kuwait",
        ["KZ"] = "Asia/Almaty",
        ["LB"] = "Asia/Beirut",
        ["LT"] = "Europe/Vilnius",
        ["LU"] = "Europe/Luxembourg",
        ["LV"] = "Europe/Riga",
        ["LY"] = "Africa/Tripoli",
        ["MA"] = "Africa/Casablanca",
        ["MD"] = "Europe/Chisinau",
        ["ME"] = "Europe/Podgorica",
        ["MK"] = "Europe/Skopje",
        ["MM"] = "Asia/Rangoon",
        ["MN"] = "Asia/Ulaanbaatar",
        ["MT"] = "Europe/Malta",
        ["MX"] = "America/Mexico_City",
        ["MY"] = "Asia/Kuala_Lumpur",
        ["MZ"] = "Africa/Maputo",
        ["NG"] = "Africa/Lagos",
        ["NL"] = "Europe/Amsterdam",
        ["NO"] = "Europe/Oslo",
        ["NP"] = "Asia/Kathmandu",
        ["NZ"] = "Pacific/Auckland",
        ["OM"] = "Asia/Muscat",
        ["PE"] = "America/Lima",
        ["PH"] = "Asia/Manila",
        ["PK"] = "Asia/Karachi",
        ["PL"] = "Europe/Warsaw",
        ["PT"] = "Europe/Lisbon",
        ["PY"] = "America/Asuncion",
        ["QA"] = "Asia/Qatar",
        ["RO"] = "Europe/Bucharest",
        ["RS"] = "Europe/Belgrade",
        ["RU"] = "Europe/Moscow",
        ["SA"] = "Asia/Riyadh",
        ["SD"] = "Africa/Khartoum",
        ["SE"] = "Europe/Stockholm",
        ["SG"] = "Asia/Singapore",
        ["SI"] = "Europe/Ljubljana",
        ["SK"] = "Europe/Bratislava",
        ["SY"] = "Asia/Damascus",
        ["TH"] = "Asia/Bangkok",
        ["TN"] = "Africa/Tunis",
        ["TR"] = "Europe/Istanbul",
        ["TW"] = "Asia/Taipei",
        ["TZ"] = "Africa/Dar_es_Salaam",
        ["UA"] = "Europe/Kyiv",
        ["UG"] = "Africa/Kampala",
        ["US"] = "America/New_York",
        ["UY"] = "America/Montevideo",
        ["UZ"] = "Asia/Tashkent",
        ["VE"] = "America/Caracas",
        ["VN"] = "Asia/Ho_Chi_Minh",
        ["XK"] = "Europe/Belgrade",
        ["YE"] = "Asia/Aden",
        ["ZA"] = "Africa/Johannesburg",
        ["ZW"] = "Africa/Harare",
    };

    public static DateTime GetLocalTime(DateTime utcTime, string countryCode)
    {
        if (!CountryTimeZones.TryGetValue(countryCode.ToUpperInvariant(), out var ianaZoneId))
            return utcTime;

        var timeZone = TimeZoneInfo.FindSystemTimeZoneById(ianaZoneId);
        return TimeZoneInfo.ConvertTimeFromUtc(utcTime, timeZone);
    }
}